// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_pJtB0ka-SRpoGG6FSSRJErUnSHVZDtg',
    appId: '1:833721022726:web:3f8f4c63eb01caa0eb4687',
    messagingSenderId: '833721022726',
    projectId: 'mood-diary-jw',
    authDomain: 'mood-diary-jw.firebaseapp.com',
    storageBucket: 'mood-diary-jw.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkyza4xszdIk6WJri-PgTift6G8LzxUng',
    appId: '1:833721022726:android:79dc4ed0abb906feeb4687',
    messagingSenderId: '833721022726',
    projectId: 'mood-diary-jw',
    storageBucket: 'mood-diary-jw.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1gk3aSXMNLPXF5q3dIEIjfvAJHF19HlE',
    appId: '1:833721022726:ios:4740fd007bafd787eb4687',
    messagingSenderId: '833721022726',
    projectId: 'mood-diary-jw',
    storageBucket: 'mood-diary-jw.appspot.com',
    iosBundleId: 'com.example.moodDiary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1gk3aSXMNLPXF5q3dIEIjfvAJHF19HlE',
    appId: '1:833721022726:ios:67b5720d7bbab6feeb4687',
    messagingSenderId: '833721022726',
    projectId: 'mood-diary-jw',
    storageBucket: 'mood-diary-jw.appspot.com',
    iosBundleId: 'com.example.moodDiary.RunnerTests',
  );
}
